import esbuild from "esbuild";
import { readFileSync } from "node:fs";
import process from "process";
import { builtinModules } from "node:module";
import { syncTestVault } from "./scripts/sync-test-vault.mjs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const SANDBOX_RUNNER_OUT = "sandbox-runner.js";

const nodeBuiltinShims = {
	path: "export default {}",
	fs: "export default {}",
	os: "export default {}",
	crypto: "export default {}",
	module: "export default {}",
};

const shimPlugin = {
	name: "node-builtin-shims",
	setup(build) {
		for (const [name, contents] of Object.entries(nodeBuiltinShims)) {
			build.onResolve({ filter: new RegExp(`^${name}$`) }, () => ({
				path: name,
				namespace: "node-shim",
			}));
			build.onLoad(
				{ filter: new RegExp(`^${name}$`), namespace: "node-shim" },
				() => ({ contents, loader: "js" }),
			);
		}
	},
};

const defineEnv = {
	"process.env.NODE_ENV": prod ? '"production"' : '"development"',
};

let sandboxRunnerCode = "";

function sandboxInlinePlugin() {
	return {
		name: "sandbox-inline",
		setup(build) {
			build.onResolve({ filter: /^@sandbox-runner-script$/ }, () => ({
				path: "index",
				namespace: "sandbox-runner-inline",
			}));
			build.onLoad(
				{ filter: /.*/, namespace: "sandbox-runner-inline" },
				() => ({
					contents: `export const SANDBOX_RUNNER_SCRIPT = ${JSON.stringify(sandboxRunnerCode)};`,
					loader: "js",
				}),
			);
		},
	};
}

function readSandboxRunnerFromDisk() {
	sandboxRunnerCode = readFileSync(SANDBOX_RUNNER_OUT, "utf8");
}

function syncVaultPlugin() {
	return {
		name: "sync-test-vault",
		setup(build) {
			build.onEnd((result) => {
				if (result.errors.length > 0) return;
				syncTestVault();
			});
		},
	};
}

const pluginContext = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	platform: "browser",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [shimPlugin, sandboxInlinePlugin(), syncVaultPlugin()],
	define: defineEnv,
});

/** IIFE for iframe srcdoc; also inlined into main.js (no runtime fetch). */
const runnerContext = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/runtime/sandboxRunner.ts"],
	bundle: true,
	format: "iife",
	platform: "browser",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: SANDBOX_RUNNER_OUT,
	minify: prod,
	define: defineEnv,
	plugins: [
		{
			name: "rebuild-main-after-runner",
			setup(build) {
				build.onEnd(async (result) => {
					if (result.errors.length > 0) return;
					readSandboxRunnerFromDisk();
					await pluginContext.rebuild();
				});
			},
		},
	],
});

async function buildAll() {
	await runnerContext.rebuild();
	readSandboxRunnerFromDisk();
	await pluginContext.rebuild();
}

if (prod) {
	await buildAll();
	process.exit(0);
} else {
	await buildAll();
	await Promise.all([pluginContext.watch(), runnerContext.watch()]);
}
