import esbuild from "esbuild";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import process from "process";
import { builtinModules } from "node:module";
import { syncAllVaults } from "./scripts/sync-examples.mjs";

const ROOT = dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

/**
 * Sandbox runner must use the host Vue instance (shared Pinia requires one Vue realm).
 * Resolves `vue` to a CJS shim that reads `window.parent.__RN_VUE_SHARED__`.
 */
function vueFromParentPlugin() {
	return {
		name: "vue-from-parent",
		setup(build) {
			build.onResolve({ filter: /^vue$/ }, () => ({
				path: "vue",
				namespace: "vue-from-parent",
			}));
			build.onLoad(
				{ filter: /.*/, namespace: "vue-from-parent" },
				() => ({
					contents: `
const shared = window.parent && window.parent.__RN_VUE_SHARED__;
if (!shared) {
  throw new Error("Reactive Notes Vue: shared Vue/Pinia runtime missing on parent window");
}
module.exports = shared.Vue;
`,
					loader: "js",
				}),
			);
		},
	};
}

const prod = process.argv[2] === "production";
const SANDBOX_RUNNER_OUT = "sandbox-runner.js";
const SANDBOX_TAILWIND_BROWSER = join(
	ROOT,
	"node_modules",
	"@tailwindcss",
	"browser",
	"dist",
	"index.global.js",
);
const SANDBOX_TAILWIND_CONFIG = join(
	ROOT,
	"src",
	"styles",
	"sandbox-tailwind.css",
);
const SANDBOX_STATIC_CSS = join(ROOT, "src", "styles", "sandbox.css");

const nodeBuiltinShims = {
	path: "export default {}",
	fs: "export default {}",
	os: "export default {}",
	crypto: "export default {}",
	module: "export default {}",
};

const shimPlugin = {
	name: "node-builtin-shims",
	setup(build) {
		for (const [name, contents] of Object.entries(nodeBuiltinShims)) {
			build.onResolve({ filter: new RegExp(`^${name}$`) }, () => ({
				path: name,
				namespace: "node-shim",
			}));
			build.onLoad(
				{ filter: new RegExp(`^${name}$`), namespace: "node-shim" },
				() => ({ contents, loader: "js" }),
			);
		}
	},
};

const defineEnv = {
	"process.env.NODE_ENV": prod ? '"production"' : '"development"',
	// Vue / Pinia compile-time flags (required when bundling into main.js)
	__VUE_OPTIONS_API__: "true",
	__VUE_PROD_DEVTOOLS__: "false",
	__VUE_PROD_HYDRATION_MISMATCH_DETAILS__: "false",
};

/** Sandbox iframe has no Node globals; mathjax-full's loader expects them. */
const sandboxDefineEnv = {
	...defineEnv,
	global: "globalThis",
	__dirname: '""',
	__filename: '""',
};

let sandboxRunnerCode = "";
let sandboxTailwindBrowserScript = "";
let sandboxTailwindConfigCss = "";
let sandboxStaticCss = "";

function sandboxInlinePlugin() {
	return {
		name: "sandbox-inline",
		setup(build) {
			build.onResolve({ filter: /^@sandbox-runner-script$/ }, () => ({
				path: "index",
				namespace: "sandbox-runner-inline",
			}));
			build.onLoad(
				{ filter: /.*/, namespace: "sandbox-runner-inline" },
				() => ({
					contents: `export const SANDBOX_RUNNER_SCRIPT = ${JSON.stringify(sandboxRunnerCode)};`,
					loader: "js",
				}),
			);
			build.onResolve({ filter: /^@sandbox-tailwind-assets$/ }, () => ({
				path: "index",
				namespace: "sandbox-tailwind-inline",
			}));
			build.onLoad(
				{ filter: /.*/, namespace: "sandbox-tailwind-inline" },
				() => ({
					contents: [
						`export const SANDBOX_TAILWIND_BROWSER_SCRIPT = ${JSON.stringify(sandboxTailwindBrowserScript)};`,
						`export const SANDBOX_TAILWIND_CONFIG_CSS = ${JSON.stringify(sandboxTailwindConfigCss)};`,
						`export const SANDBOX_STATIC_CSS = ${JSON.stringify(sandboxStaticCss)};`,
					].join("\n"),
					loader: "js",
				}),
			);
		},
	};
}

function readSandboxArtifactsFromDisk() {
	sandboxRunnerCode = readFileSync(SANDBOX_RUNNER_OUT, "utf8");
	sandboxTailwindBrowserScript = readFileSync(SANDBOX_TAILWIND_BROWSER, "utf8");
	sandboxTailwindConfigCss = readFileSync(SANDBOX_TAILWIND_CONFIG, "utf8");
	sandboxStaticCss = readFileSync(SANDBOX_STATIC_CSS, "utf8");
}

function syncVaultPlugin() {
	return {
		name: "sync-vaults",
		setup(build) {
			build.onEnd((result) => {
				if (result.errors.length > 0) return;
				syncAllVaults();
			});
		},
	};
}

const pluginContext = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	platform: "browser",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [shimPlugin, sandboxInlinePlugin(), syncVaultPlugin()],
	define: defineEnv,
});

/** IIFE for iframe srcdoc; also inlined into main.js (no runtime fetch). */
const runnerContext = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/runtime/sandboxRunner.ts"],
	bundle: true,
	format: "iife",
	platform: "browser",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: SANDBOX_RUNNER_OUT,
	minify: prod,
	define: sandboxDefineEnv,
	plugins: [
		vueFromParentPlugin(),
		{
			name: "rebuild-main-after-runner",
			setup(build) {
				build.onEnd(async (result) => {
					if (result.errors.length > 0) return;
					readSandboxArtifactsFromDisk();
					await pluginContext.rebuild();
				});
			},
		},
	],
});

async function buildAll() {
	// runner onEnd already reads sandbox artifacts and rebuilds main.js
	await runnerContext.rebuild();
}

if (prod) {
	await buildAll();
	process.exit(0);
} else {
	await buildAll();
	await Promise.all([pluginContext.watch(), runnerContext.watch()]);
}
