import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const nodeBuiltinShims = {
	path: "export default {}",
	fs: "export default {}",
	os: "export default {}",
	crypto: "export default {}",
	module: "export default {}",
};

const shimPlugin = {
	name: "node-builtin-shims",
	setup(build) {
		for (const [name, contents] of Object.entries(nodeBuiltinShims)) {
			build.onResolve({ filter: new RegExp(`^${name}$`) }, () => ({
				path: name,
				namespace: "node-shim",
			}));
			build.onLoad(
				{ filter: new RegExp(`^${name}$`), namespace: "node-shim" },
				() => ({ contents, loader: "js" }),
			);
		}
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	platform: "browser",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [shimPlugin],
	define: {
		"process.env.NODE_ENV": prod ? '"production"' : '"development"',
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
